#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""伪满皇宫博物院官网「藏品」栏目的全部藏品。

来源：https://www.wmhg.com.cn（抓取 2026-09-24，`wmhg_site_scrape.py --scrape` 生成，**勿手工编辑**）
中文 29 件、英文 24 条。**两套 id 不相通**（中文 /collection/detail/<id>，
英文 /en/collection/detail/<id>），英文是中文那批的机翻，配对在 wmhg_build.py 里做，不在这里。

每条字段逐字照录：name（详情页标题）、list_name（列表上的名称）、category_id/category（类目）、
url、images（详情页轮播图）、desc（简介正文，按段落分行；开头的「简介」「Introduction」标签已去掉）。
**desc 不拆字段** —— 尺寸、作者、年代都写在正文里，写法不一（AGENTS.md 第 7 条）。
英文 1793 标题是「Collection testdata Porcelain …」，照录，由 wmhg_build.py 处理。
"""

ZH: dict[str, dict] = {
    '5': {
        'id': '5',
        'name': '大山雅堂《布袋和尚戏婴图》',
        'list_name': '大山雅堂《布袋和尚戏婴图》',
        'category_id': '14',
        'category': '日本画',
        'url': 'https://www.wmhg.com.cn/collection/detail/5.html',
        'images': ['/Uploads/Picture/2019/05/07/s5cd137cb56a40.jpg', '/Uploads/Picture/2019/05/07/s5cd137cc196b5.jpg', '/Uploads/Picture/2019/05/07/s5cd1380ac114a.jpg'],
        'desc': '作者为:大山雅堂，生于1902年（明治三十五），枥木县人，师承小室翠云，此画是他的经典力作。\n此画为立轴丝质，画心纵119.5厘米，横41.5厘米，画中，“布袋和尚”契此容颜喜人，双耳饱满，肩宽肚圆，神情慈爱。他正与两个孩童玩耍嬉戏，只见他袒着胸，光着脚，禅杖也索性扔到了地上，两手紧攥着布袋两角，把布袋当成了摇篮，将一个大约一、两岁的孩童包裹起来，来回荡漾。孩童很是开心，欢呼雀跃地将小手伸向空中，契此和蔼可亲地望着欢喜的孩童，慈祥的目光里充满着无尽的怜爱与疼惜。另一个四、五岁的孩童则藏在契此身后，羞涩地撩起了他的僧袍遮挡面部，向外探望的眼眸，清澈无邪，净是孩子的天真烂漫、稚气未脱。画家以柔和的线条，缓缓绘出了三位人物的神态心境，造型生动准确，笔法细腻传神，着色淡雅清新。简约温馨的画面，洋溢着浓浓的爱的温情，此时的契此仿佛不再是一个出家人，而更像是一位慈爱的母亲；或者说，此时布袋中的婴孩，也不再是无忧的顽童，而是尘世间的芸芸众生。契此如同佛祖一般，安静祥和地凝望着滚滚红尘、茫茫人海，微微的泯笑之中，难掩慈爱与悲悯之情。',
    },
    '155': {
        'id': '155',
        'name': '日本青花斗彩花卉纹尊',
        'list_name': '日本青花斗彩花卉纹尊',
        'category_id': '13',
        'category': '瓷器',
        'url': 'https://www.wmhg.com.cn/collection/detail/155.html',
        'images': ['/Uploads/Picture/2019/04/29/s5cc6c93a8272a_932_436_103_0.png', '/Uploads/Picture/2019/04/29/s5cc6c9543899c_962_449_0_0.png', '/Uploads/Picture/2019/04/29/s5cc6c93a71564_1088_508_79_0.png'],
        'desc': '该尊高18.7厘米，口直径9.6厘米，足直径9.3厘米，底部中间有手书“今右卫门”款识。器物胎质较厚，釉质清澈明亮，釉面上有较强的玻璃光泽。器物中下部彩绘多朵花卉，红彩施之格外醒目，足外青花竖条装饰简单明快。',
    },
    '156': {
        'id': '156',
        'name': '七宝烧红地小花瓶',
        'list_name': '七宝烧红地小花瓶',
        'category_id': '13',
        'category': '瓷器',
        'url': 'https://www.wmhg.com.cn/collection/detail/156.html',
        'images': ['/Uploads/Picture/2019/11/14/s5dcd0d06bfe4e_5590_2613_631_0.jpg'],
        'desc': '简介：\n此瓶为一对，铜胎，敞口，短颈，丰肩，直腹，下敛，矮圈足。高12.5厘米，口径4.2厘米，底径5.6厘米，重1570克，烧制年代为伪满时期。此瓶造型奇特，瓶身有两组对称凹线，通体枣红色珐琅地，釉色精致，明灿莹润，所绘树木和花鸟气韵雅致，色彩丰富而不华丽，层次井然，生动唯美。在枣红色背景的柔和映衬下，月光如水，落英缤纷，绿树和白花交错生长，暮色与柔光交相辉映。繁叶翠色欲滴，花朵嵌苞待放，灵动的鸟儿双栖在枝桠之间，面对着这样一幅唯美恬静的自然画卷，观者仿佛置身于浓郁繁茂的树荫之下，清嗅着花儿甜蜜的芬芳，倾听着鸟儿愉悦的欢鸣，情趣盎然，宛若仙境。\n通体观之，此瓶构思巧妙，仪态大方，在厚重感中不乏生动，在看似粗糙的表面又精细入微。更难能可贵的是，两瓶的大小、色泽、图饰和重量都完全一致，同出一辙，体现了当时制作工艺的精湛超群。双瓶保存完好，1982年8月，由吉林省博物院调拨伪满皇宫博物院收藏，国家三级文物。',
    },
    '258': {
        'id': '258',
        'name': '日本大正十四年菊花御纹章银杯',
        'list_name': '日本大正十四年菊花御纹章银杯',
        'category_id': '17',
        'category': '宫廷文物',
        'url': 'https://www.wmhg.com.cn/collection/detail/258.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d0748c88a2cd_3197_1489_347_0.JPG', '/Uploads/Picture/2019/06/17/s5d07496708ce9_3179_1481_0_0.JPG'],
        'desc': '简介：\n此件文物直径：7.8厘米，足径：2.2厘米，高：2.6厘米，重：86克。此杯是大正十四年，即1925年，为纪念大正天皇天后结婚25周年庆祝仪式所特制，用以赏赐群臣，杯内刻有十六瓣八重表菊纹。此杯圈足内刻有“纯银三越”字样。日本银制品的加工和使用，可以追溯至古坟时代。从明治中期开始，在日本各地涌现出大量以贵金属制品为主业的商家，三越百货公司（吴服店）便是其中之一，“一战”以后，该店成为日本银器的主要生产者和经营者。',
    },
    '466': {
        'id': '466',
        'name': '日本七宝烧菊花纹大瓶',
        'list_name': '日本七宝烧菊花纹大瓶',
        'category_id': '13',
        'category': '瓷器',
        'url': 'https://www.wmhg.com.cn/collection/detail/466.html',
        'images': ['/Uploads/Picture/2019/04/29/s5cc6c5821b096_918_430_130_0.png', '/Uploads/Picture/2019/04/29/s5cc6c5822c511_931_435_114_0.png', '/Uploads/Picture/2019/04/29/s5cc6c5ce5f2d9_876_409_105_0.png'],
        'desc': '简介：\n该瓶高61.5厘米，口径21.5厘米，足径54.5厘米，重10723克。色泽枣红，胎质为银，敞口大足，肩宽腹丰，器型典雅庄重，玻璃质感光耀如水，红色灿烂夺目，瓶的中部以掐丝工艺制作了两株盛开的菊花，在菊花的右下角错落生长着几株兰花。此瓶是日本七宝烧中的精品。',
    },
    '470': {
        'id': '470',
        'name': '日本青花开光盆景纹小罐',
        'list_name': '日本青花开光盆景纹小罐',
        'category_id': '13',
        'category': '瓷器',
        'url': 'https://www.wmhg.com.cn/collection/detail/470.html',
        'images': ['/Uploads/Picture/2019/06/27/s5d14628a2956e.jpg', '/Uploads/Picture/2019/04/29/s5cc6c4a17e2a5_967_452_100_0.png', '/Uploads/Picture/2019/04/29/s5cc6c4b6aaeb8_997_466_0_0.png'],
        'desc': '简介：\n此罐高12.3厘米，口径3.1厘米，腹径9.3厘米，足径5.2厘米，重480克。小口，球形腹浑圆，圈足，足内施白釉，以青花书“九谷旭山”楷书款。通体青花纹饰，罐体自上而下分为四层，每层以细弦纹和留白间隔；口沿下饰串珠纹，肩部有八个万字团纹均匀分布；腹部有四处叶状的菱形开光，内绘湖泊亭台、人物树木；菱形四角均有三朵祥云相衬，开光区域以四叶一朵二方连续纹间隔，近足处绘变体莲纹一周。',
    },
    '471': {
        'id': '471',
        'name': '日本今右卫门青花加彩花卉纹尊',
        'list_name': '日本今右卫门青花加彩花卉纹尊',
        'category_id': '13',
        'category': '瓷器',
        'url': 'https://www.wmhg.com.cn/collection/detail/471.html',
        'images': ['/Uploads/Picture/2019/04/29/s5cc6c32ac5fc7_987_461_98_0.png', '/Uploads/Picture/2019/04/29/s5cc6c32ad40e3_977_457_92_0.png', '/Uploads/Picture/2019/04/29/s5cc6c29654da6_817_382_120_0.png'],
        'desc': '此尊高18.5厘米，口径9.6厘米，腹径13.8厘米，足径9.9厘米，重1000克。敞口，垂腹，圈足，足内以青花书“今右门”草书款。通体施白釉，身两侧对称绘有牡丹和菊花等花卉，近足处绘竖条纹饰一周。釉色乳白如凝脂，构图疏朗有致，花色艳丽饱满，青花和添彩烘托相衬，体现自然和谐之气。',
    },
    '473': {
        'id': '473',
        'name': '冈本大更《布袋和尚画像》',
        'list_name': '冈本大更《布袋和尚画像》',
        'category_id': '14',
        'category': '日本画',
        'url': 'https://www.wmhg.com.cn/collection/detail/473.html',
        'images': ['/Uploads/Picture/2019/05/07/s5cd136efddb02.jpg', '/Uploads/Picture/2019/05/07/s5cd138f5b8eab.jpg', '/Uploads/Picture/2019/05/07/s5cd13929d410c.jpg'],
        'desc': '作者为：冈本大更，生于1879年（明治十二），字直道，三重县生人。东京美术学校毕业，大每代理部画道讲习会教师，亦于自宅创办更彩画塾。画心纵111.7厘米，横36厘米，绢本设色，包首折残。画中，契此手握一杆禅杖，泰然自若、悠然自得地禅坐在鼓鼓的大布袋之上。他顶有肉髻，阔耳垂肩、墨腮红唇、身姿饱满，神情温和。朴素的僧袍松垮地披在肩上，古朴的禅杖轻轻地握在手中，鼓胀充盈的布袋，载着他庞大丰硕的身躯，仿佛云朵一样漂浮在明净浩渺的天空之中，整个画面给人一种雍容不迫、内敛深沉、睿智大度之感。他袒露的胸膛、便便的大肚，将豁达不羁、淡泊随意的胸怀表露无遗；他亲切和蔼的目光、泯然微笑的嘴角，使悲天悯人、仁慈博爱的心境呼之欲出。画作用笔娴熟，圆转流畅，墨韵生动，骨力老到，笔到而神采毕现。在色彩的浓与淡，空间的虚与实之间，营造出了一种悠然空灵的仙人意境。',
    },
    '474': {
        'id': '474',
        'name': '松村景文《禅狐图》',
        'list_name': '松村景文《禅狐图》',
        'category_id': '14',
        'category': '日本画',
        'url': 'https://www.wmhg.com.cn/collection/detail/474.html',
        'images': ['/Uploads/Picture/2019/05/07/s5cd13d96459a1_4730_2211_427_0.JPG', '/Uploads/Picture/2019/05/07/s5cd13dfcca18f_929_434_0_46.jpg'],
        'desc': '作者:日本江户时代著名的圆山四条派绘画大师——松村景文。名直治，字士藻、子藻，号华溪，通称要人。生于日本京都，绘画家学渊深，是四条派创始人松村吴春最小的弟弟。\n《禅狐图》原名《野狐垂钓图》，设色纸本，立轴，款识为景文。通纵:102.5厘米,通横:43厘米；画心纵:27.8厘米,画心横：46厘米。此画属水墨写意，画中一只狐狸正襟危坐，头戴围巾，身着裙服，腰系丝绦，右手持竹杖，神态安详自若，双目若睁若闭，似在专心冥想，又似把竿垂钓，其状甚为专著、执着，意趣盎然，拙趣横生。该画笔法精到，用墨清新，简练明快，虚实结合，只寥寥数笔便勾勒出一只生动可爱、拟人化了的狐狸，流畅朴素的水墨线条，流露出浓郁的中国明清写生画的风格。此作品除画心所绘狐狸外，便无他物，这大面积的留白仿佛给人一种“万物隐退，空灵无迹，视之无形，听之无声”之感，但细细品味，在这无形无色的虚空之中，却蕴含着生命的流动与沉淀，衬托出画中笔墨无限的柔美与张力，给人以无尽的遐想。',
    },
    '475': {
        'id': '475',
        'name': '渡边华山《武士之女》',
        'list_name': '渡边华山《武士之女》',
        'category_id': '14',
        'category': '日本画',
        'url': 'https://www.wmhg.com.cn/collection/detail/475.html',
        'images': ['/Uploads/Picture/2019/05/07/s5cd134bd4c40d.jpg'],
        'desc': '渡边华山（ 1793—1841），原名渡边定静、字子安、一字伯登，通称登，号华山，而且多以此号行世，他既是画家，又是学者兼政治家。华山十分注重写生，他的山水画吸取大自然的精华，天地的秀气，作品多清雅淡逸、信笔遣兴。作品既运用了中国水墨画的程式、皴法，同时又吸收西方的透视法、造型学，整幅画面远近层次分明，把文人画的笔墨韵化与西洋画的表现方法巧妙融合，再注入本国的民族风格，从而形成了自己新的传统的文人画风貌。\n此画绢本设色，画心纵40.5厘米，横57厘米，由国家文物局专家鉴定组鉴定为一级文物。\n渡边华山以擅画人物著称。这幅《武士之女》属传统的绘画风格，工笔人物画，画卷装裱考究，无题跋，只署穷款：“华山戏墨”。\n画中所绘一位日本女子，身着和服，头饰素栉，双目凝神，回望飞燕，肌肤似雪，青丝如云，柳叶有情，樱桃微启，表现了江户时代贵族女子雍容华贵、安详恬静、风情万种的优雅神态。此画具有鲜明的日本民族风格和浓郁的人文精神，细微之处又显露出中国传统仕女绘画艺术的痕迹。画中人物仪态端庄，衣裳简劲，色彩柔丽，清雅中不失娇美，淡定中不失活力，在其扶栏顾盼的瞬间，生动唯美，气韵传神，流露出她丰富多情的内心世界和看似柔弱内敛、实则蓬勃坚韧的生命气质。常言道：“容情入境，心如其画”，此画表现了作者深邃细腻、志趣高雅的审美境界和独特精湛的艺术修养。\n画中女子身着深褐色和服，腰间系着黄绿相间的花样锦结，锦结上绣着洁白的七瓣菊花。日本天皇家族自镰仓时代开始，将十六瓣金黄色的菊花图案定为家纹，名曰“菊花御纹章”，并颁布法令，禁止皇族以外的平民使用，但天皇也会把不同花样的菊纹下赐给众多功绩显赫的武将，由此可以证明，画中女子出生于尊贵的武士家庭。画中，她用左手依扶栏杆，手腕处清晰可见一片绯红的襦袢。德川幕府时期，红色因其具有兴旺、繁荣、力量如同朝日的寓意被禁止平民使用，只有幕府的贵族才可使用。德川家康为了笼络众臣，在高兴之时也会赏赐给他的部下，由此可以再次断定画中女子出身于名门望族。日本武士产生于平安时代，九世纪中期，一些地方领主开始建立私人武装，用其扩张势力。这种武装逐渐成熟为一种制度化的专业军事组织，其基础是宗族和主从关系。到了十世纪，朝廷无力镇压地方势力的叛乱，不得不借助各地武士的力量，武士更进一步得到了中央的承认，成为日本的特权统治阶级。\n平安时代，日本贵族开始流行剃眉染齿的习俗。在《枕草子》、《紫式部日记》等书中都有记载:“着装(女子成人式)、庆祝日，众妇人皆染黑齿、红赤化妆。”最初作为成人标准，女孩子在成人礼这一天染齿，后来染齿的时间不断变化为订婚之日、结婚前一天晚上、生孩子时，最后逐渐演变成为区别已婚者与未婚者的标志。值得一提的是，不仅是女人，连公卿和武士，也以染齿为美，男子元服(成人式)也要染齿。当时著名的武士平敦盛是一位翩翩美少年，他上阵前一定要先化妆、染黑齿，一度传为佳话。黑齿是由一种专门的铁浆染成的，将铁屑浸入酒、茶、醋中使其出黑水，然后用羽毛、笔刷涂在牙齿上。据说，染齿除了更符合日本人的审美标准，同时还有防蛀牙的优点。在《堤中纳言物语》中记载，虫姬长的漂亮可爱，只因末染齿，无人招为妻，可见当时日本女人如果不将牙齿染黑是不能出嫁的，由此可以判定这位武士的女儿还没有婚嫁。',
    },
    '476': {
        'id': '476',
        'name': '渡边华山 《寒林群鸦图》',
        'list_name': '渡边华山 《寒林群鸦图》',
        'category_id': '14',
        'category': '日本画',
        'url': 'https://www.wmhg.com.cn/collection/detail/476.html',
        'images': ['/Uploads/Picture/2019/05/07/s5cd135e06b88a.jpg', '/Uploads/Picture/2019/05/07/s5cd1362254927.jpg', '/Uploads/Picture/2019/05/07/s5cd136225f637.jpg'],
        'desc': '作者：渡边华山(1793-1841)，原名渡边定静，字子安，一字伯登，通称登，号华山，多以此号行世。斋号有寓绘堂、全乐堂、金暾居、昨非居士、随安居士。此画属高远山水画，纸本水墨，立轴，行书款：“天保丁酉嘉平月写于全乐堂，华山外史登。”款下钤章两枚：一为白文小篆长方图章“鸥保”，二为朱文小篆葫芦形“登”字章。此画通纵：187厘米，通横：67.4厘米；画心纵：124厘米，画心横：53厘米。画中所绘为深秋的原野，群鸦迁徙，万物萧条的凄凉景象。峰峦、树丛、溪水、丘石，分层交叉，错落有致，由近及远，由远及近；成群结队的乌鸦在千崖万壑之间低旋徘徊；清冷的溪水，紧绕孤零零的荒山；曲径陡途之上，一老叟执杖仰首前行，一书童抱琴随侍身后，笼罩这一老一小的，是暮秋袭人的凉意和林间阵阵的哀鸣。他们要穿越枯树寒林的荒凉与苍茫，走进隆冬岁末的寂静与凄清。浑然苍朴的画面，雄肆奔放的笔力，纵横跌宕的气势，万里悲秋的情怀，表达了作者对日本民族未知前途的深深忧虑和自己身处人生低谷的无奈与苍凉。',
    },
    '477': {
        'id': '477',
        'name': '喜多川龟麿《出游图》',
        'list_name': '喜多川龟麿《出游图》',
        'category_id': '14',
        'category': '日本画',
        'url': 'https://www.wmhg.com.cn/collection/detail/477.html',
        'images': ['/Uploads/Picture/2019/05/07/s5cd12f22ca204.jpg', '/Uploads/Picture/2019/05/07/s5cd12f2334b1e.jpg', '/Uploads/Picture/2019/05/07/s5cd12f22c03da.jpg'],
        'desc': '喜多川龟麿这幅浮世绘作品《出游图》，画心纵97厘米，横38.5厘米，全部为日本原裱，质地为丝，画面微微泛黄，装裱材料上托以金色折扇形状，给人以富丽堂皇之感，使整幅画都充满了贵族气息，此画作属肉笔浮世绘。展开这幅《出游图》的画卷，首先映入眼帘的是一幅秋意浓浓的出游场景。远处山峦起伏，画面右侧山涧处突出的山石隙里有几株花枝，枝上盛开着鲜花，从山涧上飞泄而下的瀑布有如白练，溅起点点水花，云雾与水气相映，衬托出远处画面的云雾缭绕，有如仙境一般，画面近处所绘的四个人物，最前面的女子衣着华贵，手拿象征身份和品级的穿穗柏木折扇。人物的姿态高贵、典雅，透露出古典美人的神韵。其身后跟随着两名侍女，她身后左侧的侍女一边双手持粉红色阳伞为其遮阳，一边回首象后方望去，似被什么吸引；而另一名侍女则双手托一锦盒，紧随在女子身后，似随时准备听候她的差使；而紧跟在这个侍女身边的小女孩儿满脸的稚气与天真，她跟随在侍女身后，好象被身的美景吸引不忍离去。在她们的身后鲜花盛开，在配之以艳丽的服饰，使整幅画面处处都渗透着秋的韵味。画面人物的服饰色彩鲜明，画家即展现了服饰的绚丽、华美，同时还严格的按照人物的社会地位、等级来选择服饰的颜色。而且，将女子华丽的、高贵的服饰恰到好处的展现出来。画家在山石和人物的处理上运用了对比的手法，线条的运用即反映出画家的品性、情趣，同时也传达出了画家精细入微而又丰富的意蕴和情感，体现了龟麿这位浮世绘画家细腻的、极善于表现女子柔媚的绘画风格。',
    },
    '478': {
        'id': '478',
        'name': '日本黄釉凤纹七宝烧瓶',
        'list_name': '日本黄釉凤纹七宝烧瓶',
        'category_id': '13',
        'category': '瓷器',
        'url': 'https://www.wmhg.com.cn/collection/detail/478.html',
        'images': ['/Uploads/Picture/2019/04/29/s5cc6c1c41a5e8_894_418_-3_0.png', '/Uploads/Picture/2019/04/29/s5cc6c1e6ca7e5_846_396_0_0.png', '/Uploads/Picture/2019/04/29/s5cc6c1a3a8d79_839_392_112_0.png'],
        'desc': '此瓶铜胎，敞口，短颈，丰肩，直腹，平足。高36厘米，口径15.3厘米，底径15.3厘米，重4720克，烧制年代为伪满时期。该瓶通体金黄色珐琅地，正中央描绘了一只展翅翱翔的五彩凤凰，冠如雄鸡呈赤色，硕大张扬；颈如蛇呈青色，绒毛直耸；翅如鹏呈绿棕黑相间，由深渐浅；足如鹤呈褐色，自然舒展；尾如孔雀呈五彩，随风飘逸。此只凤凰在腾空起舞的瞬间，傲然俯视苍穹，仪态高贵优美，翎羽大气舒展，气势强劲如虹，在金黄色背景的映衬下，更显君临天下之态，彰显了百鸟之王的神韵和风采。凤凰亦称为凤皇、朱鸟、丹鸟、火鸟和鹍鸡。“凤”和“凰”在古老神话中原本是两种不同的神鸟，后世人通常将凤和凰解释为雌雄不同的同一种鸟，即雄为凤，雌为凰，雌雄统称。凤为中国古代动物四灵之一，有浴火重生的本领，故有“不死鸟”的美誉，它与龙一起构成了龙凤文化，是中国传统文化的两翼，是中华民族追求“龙凤呈祥”和谐精神的象征。日本民族自古也以“鸟”为图腾，并受中国传统文化的影响把凤凰作为神鸟，寓意祥瑞之意，中日两国的文化渊源也由此可见一斑。',
    },
    '479': {
        'id': '479',
        'name': '伪满大典纪念章',
        'list_name': '伪满大典纪念章',
        'category_id': '16',
        'category': '纪念章',
        'url': 'https://www.wmhg.com.cn/collection/detail/479.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d0745762c2da_5584_2601_354_0.JPG', '/Uploads/Picture/2019/06/17/s5d07458cc6072_5584_2601_505_0.JPG'],
        'desc': '为了庆祝“旷古大典”特别制作了“大典纪念章”，并明文规定了领授的范围：1、被召参与大典及其关系者；2、参加御大典事务及其关系者；3、其他由国务总理指定者。傀儡登极当日，大大小小伪官吏均佩戴“大典纪念章”参加溥仪的“登极大典”。此章银质园形，直径3.5厘米，正面上嵌有金色兰花御纹章，下铸竖排“帝出乎震”4个银色文字，两侧刻有对称的凤凰图案。背面，正中铸有“大典纪念章”，右侧铸有“康德元年”，左侧铸有“三月一日”，均系银色文字。该章上方有一银质园环，系以红白黄黑兰柳条丝织章绶。帝出乎震四个字，最早见于《文王八卦方位图》中，“帝出乎震。齐乎巽”。后世有学者认为，这里的“帝”实际指的是北斗星中的“帝星”，四个字的本意是“帝星出现在西边的天空中”。',
    },
    '480': {
        'id': '480',
        'name': '伪满东边道讨伐纪念章',
        'list_name': '伪满东边道讨伐纪念章',
        'category_id': '16',
        'category': '纪念章',
        'url': 'https://www.wmhg.com.cn/collection/detail/480.html',
        'images': ['/Uploads/Picture/2019/06/27/s5d14589ca89bf.jpg', '/Uploads/Picture/2019/06/27/s5d145b3ede553.jpg'],
        'desc': '为了纪念“围剿”抗日将领王凤阁行动“成功”，日本侵略者特别面向参加东边道“大讨伐”的日军将领发行为数极少的“东边首讨伐纪念章”。该章圆形，直径5cm，镀银。纪念章一面左上角阳刻着十字带，中间阳刻黄色五角星，在五角星的左下方写有“一畈”，中部由一条河分开，河的上部为高山丛林，河的下方为一只展翅的鸟，在鸟的肚子上刻有“王凤阁”三个黄色的字。另一面最上方有两行字：第一行字写着“1937.3.27”，第二行写着“东边道讨伐”。下方是东边道地形图，有“奉天”和“通化”的位置。',
    },
    '481': {
        'id': '481',
        'name': '伪满建国神庙创建纪念章',
        'list_name': '伪满建国神庙创建纪念章',
        'category_id': '16',
        'category': '纪念章',
        'url': 'https://www.wmhg.com.cn/collection/detail/481.html',
        'images': ['/Uploads/Picture/2019/05/29/s5cee3715a4c55.jpg', '/Uploads/Picture/2019/05/29/s5cee372349a9f.jpg'],
        'desc': '溥仪发布《国本奠定诏书》，把“天照大神”定为“满洲国”的“国神”。规定每年的7月15日为“建国神庙”创建纪念日，放假一天，并要求学生、士兵必须把诏书背诵如流，背不下来或者是背错的就要受到严厉的惩罚。与此同时伪满政府还发布了《对于建国神庙及其摄庙不敬罪处罚法》，规定无论任何人走过神庙，都要行九十度的鞠躬礼，否则就按“不敬处罚法”加以惩治。为纪念这件“大事”，伪满政府还专门制作“建国神庙创建纪念章”。 纪念章为黄铜质，圆形，直径3 cm，厚0.3 cm，上有环形穿孔。纪念章的正面是伪满时期“建国神庙”的图案，背面中间写有“建国神庙创建纪念章”字样，右边为：康德七年，左边为：七月十五日。',
    },
    '482': {
        'id': '482',
        'name': '伪满皇帝访日纪念章',
        'list_name': '伪满皇帝访日纪念章',
        'category_id': '16',
        'category': '纪念章',
        'url': 'https://www.wmhg.com.cn/collection/detail/482.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d074493867c2_5584_2601_480_0.JPG', '/Uploads/Picture/2019/06/17/s5d0744ac19421_5584_2607_575_0.JPG'],
        'desc': '为了纪念溥仪访日，伪满政府制作发行纪念章一枚。纪念章的图案委托日本著名的雕刻家日名子实三设计，大阪造币局制作。该章为银质镞形，规格为长3.8 厘米，宽3 厘米，厚0.35 厘米，表面突起，正面雕铸多层象征伪满洲国的兰花和象征日本国的菊花的花卉图案，花束下雕有彩带，彩带上面铸有“一德一心”四字。背面从右至左刻有“康德四年”“满洲帝国皇帝访日纪念章”“四月六日”三行字。章上面有一长6厘米，宽3.8厘米的中央深紫色，两边红色的绶饰。其中红边宽为0.3厘米*2，中央深紫色宽为3.2厘米。按照1935年9月颁布的“满洲帝国皇帝访日纪念章令”规定，纪念章发放的范围为：（一）直接从事于康德二年四月皇帝访问日本国皇室事务者。（二）关于伴随此项要务者。(三)贡献于皇帝访问日本国皇室趣旨之闸明者。',
    },
    '483': {
        'id': '483',
        'name': '伪满建国功劳章',
        'list_name': '伪满建国功劳章',
        'category_id': '16',
        'category': '纪念章',
        'url': 'https://www.wmhg.com.cn/collection/detail/483.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d07442df1fec_5584_2601_379_0.JPG', '/Uploads/Picture/2019/06/27/s5d145c90ed205.jpg'],
        'desc': '建国功劳章是溥仪经咨询“参议府”后“裁可”以“教令”形式公布制定的一种奖章，该章为铜质圆形，直径30厘米，正面嵌有银质“建国”二字，字的两边各有一株弓形高粱，高粱穗也为银质镶嵌。背面从右至左铸有三竖行字“大满洲国”“建国功劳章”“大同元年”。丝织章绶宽为35厘米,由黑、白、黄、红、蓝五种象征日、满、朝、蒙、汉五族协和的五色旗，其中黑色为5厘米,白色为5厘米,黄色为15厘米,红色为5厘米,蓝色为5厘米。1934年3月1日，在伪满洲国政府实现帝制的同时，又颁布了新的组织法，在其中规定“皇帝可受与勋章等其它荣誉褒赏”。并按规定，在国务院总务厅设立恩赏处，由总务厅人事处处长皆川丰治兼任处长，下设总务、调查两科，负责办理勋、奖章、纪念章及其他荣誉褒赏等事项。',
    },
    '488': {
        'id': '488',
        'name': '忠灵塔铜镜',
        'list_name': '忠灵塔铜镜',
        'category_id': '18',
        'category': '铜镜',
        'url': 'https://www.wmhg.com.cn/collection/detail/488.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d074abbc98ee_3054_1422_318_0.JPG', '/Uploads/Picture/2019/06/17/s5d074accccc42_3054_1426_311_0.JPG'],
        'desc': '简介：\n此铜镜直径7.6厘米，缘厚0.6厘米，重192.4克，多边葵花型，无镜钮，窄沿，质地紫铜。镜面微凸，中间圆形环饰内有日语铭文，大意是：“御制，为了国家阵亡的将士，其名字将永远镌刻在忠灵塔之上，永世留芳，纪元二千六百年纪念”。镜背由如意型曲线分作内外二区，内区主题突出，高浮雕塑“忠灵塔”，塔上方呈放射状条纹，寓意“光芒万丈”，塔下方有湖水和鲜花围绕。外区正上方铸有铭文“新京”二字，其余空间为花草修饰。镜缘最下方不再是葵花型曲线，取而代之的则是一把战刀图案。这枚带有伪满洲国“新京”忠灵塔图案的铜镜，铸于1940年，为庆祝日本皇纪2600年纪元年而造。日本是一个神道国家，日本民族自称是“天照大神”的后代，从神武天皇诞生时起到裕仁天皇执政的昭和17年，正好是2600整年，因此这一年，成为日本百年一遇的大庆之年。日本关东军卵翼下的伪满洲国，在其主子的指使下，也大肆举行各种庆祝和纪念活动。此枚铜镜的铸造，一方面是祭奠日本在侵略战争中战死的亡灵，欺骗日本本土的民众和中国东北的伪军继续为大东亚圣战卖命；另一方面强迫东北人民庆祝日本天皇制诞生2600年，进而宣扬“日满一体”、“一德一心”，对中国人民实行思想麻醉和精神奴役。',
    },
    '489': {
        'id': '489',
        'name': '御岳教关东大教会纪念铜镜',
        'list_name': '御岳教关东大教会纪念铜镜',
        'category_id': '18',
        'category': '铜镜',
        'url': 'https://www.wmhg.com.cn/collection/detail/489.html',
        'images': ['/Uploads/Picture/2019/06/27/s5d141e38333fa.jpg', '/Uploads/Picture/2019/06/17/s5d074a1eb1b05_1229_574_438_0.jpg'],
        'desc': '简介:\n此铜镜直径7.6厘米，缘厚0.7厘米，重189.7克，造型为八角葵花型，圆钮，窄沿。镜面上刻有日语铭文，大意是：“每日对镜自省，可以修炼身心”；镜背以镜钮为中心，左右两只凤凰脚踏祥云，相对起舞，凤体丰腴柔健，凤足轻盈婀娜，凤尾飞动舒展。双凤迎风展翅间，颈部所系花带也随之飘扬，栩栩如生。双凤头顶，凤尾簇拥之处有一六边花纹图饰；镜下方铸有铭文：“御岳教关东大教会开教三十年纪念”。 此枚铜镜铸于1942年，为庆祝御岳教关东大教会在中国东北开教三十年，由此可见，神道教作为伪满洲国的国教，是侵略者统治和愚弄东北人民思想的重要工具，宗教侵略是日本实行殖民统治的“精神鸦片”。',
    },
    '491': {
        'id': '491',
        'name': '玉翁周县长去思纪念铜镜',
        'list_name': '玉翁周县长去思纪念铜镜',
        'category_id': '18',
        'category': '铜镜',
        'url': 'https://www.wmhg.com.cn/collection/detail/491.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d0749b798b43_3054_1422_249_3.JPG', '/Uploads/Picture/2019/06/17/s5d0749cba7ea1_1631_760_295_0.jpg'],
        'desc': '简介：\n此铜镜直径41.3厘米，缘厚1.6厘米，重6320克，圆形, 镜身平直，圆钮顶平，素宽沿，体积硕大，镜面以右至左布满了铭文：最上端中央用篆字铸有“万家之佛”；右侧为：“玉翁周县长去思纪念”；左侧为：“阿城县政绅商农学各界颂”。圆形是中国铜镜最古老、最传统的器形，也是丰满、完整、吉祥、美好、富足的象征。去思，谓地方士民对离职官吏的怀念。语出《汉书·何武传》：“欲除吏，先为科例以防请託，其所居亦无赫赫名，去后常见思。”镜中央的楷体正文，表达了阿城县社会各界，对前任县长的敬重和怀念，以及对其政绩功德的歌颂。镜背以镜钮为主心上下左右分别铸有铭文“福寿荣祥”，在顶端“福”字两侧铸有“吕家包换”的字样，“吕家”是当时阿城县铸镜作坊的名号，“吕家包换”是对其铜镜质量的一种保证和承诺。',
    },
    '493': {
        'id': '493',
        'name': '日本昭和三年菊花御纹章银杯',
        'list_name': '日本昭和三年菊花御纹章银杯',
        'category_id': '17',
        'category': '宫廷文物',
        'url': 'https://www.wmhg.com.cn/collection/detail/493.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d0748790f723_3197_1492_351_0.JPG', '/Uploads/Picture/2019/06/17/s5d07488da0680_3197_1489_217_4.JPG'],
        'desc': '简介：\n此件文物直径：8.8厘米，足径：3.1厘米，高：3.1厘米，重：94.7克。1926年12月25日，大正天皇病逝，裕仁天皇登基。1928年11月10日，裕仁天皇在京都举行了隆重的即位大礼，此杯是大礼时天皇皇后下赐之物，杯内刻有十六瓣八重表菊纹。',
    },
    '494': {
        'id': '494',
        'name': '日本昭和三年菊花御纹章矛型糖盒',
        'list_name': '日本昭和三年菊花御纹章矛型糖盒',
        'category_id': '17',
        'category': '宫廷文物',
        'url': 'https://www.wmhg.com.cn/collection/detail/494.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d0747fc0ebe7_5584_2607_928_0.JPG', '/Uploads/Picture/2019/06/17/s5d07481cea85b_5584_2601_379_6.JPG'],
        'desc': '简介：\n此件文物边长：3.5厘米，高：7厘米，重：80克。这种糖盒从明治维新之后开始流行，最早出现的记录在明治21年（1888），是天皇在举办各种招待会、庆典和其他礼仪性活动期间，于宴会上“下赐”来宾的常规礼品。此后，一些贵族也学习皇室做法将之作为结婚祝寿、加官进爵相关宴会上的纪念物。这一风潮继续扩大，军政系统和企业机构也纷纷效仿，但是在“二战”之后，又基本恢复到以皇室为主的状态。此糖盒为裕仁天皇举行即位大礼时的御赐之物，用来装日本的传统糖果“金平糖”。',
    },
    '495': {
        'id': '495',
        'name': '伪满兰花御纹章长方型糖盒',
        'list_name': '伪满兰花御纹章长方型糖盒',
        'category_id': '17',
        'category': '宫廷文物',
        'url': 'https://www.wmhg.com.cn/collection/detail/495.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d07475b5d929_3197_1492_473_0.JPG'],
        'desc': '简介：\n此件文物长：6.1厘米，宽：4.8厘米，高：2.3厘米，重：101克。此糖盒是伪满皇宫建国神庙建成时，溥仪在宴请群臣的宴会上，用它来装日本的传统糖果“金平糖”，这与日本天皇下赐糖盒有异曲同工之处。盒盖上有兰花御纹章标记，底部有“纯银生驹”字样。1870年，権七生驹在日本大坂成立了专门从事银制品和珠宝生产的生驹商铺。1923年，生驹株式会社正式成立，这个家族企业为日本皇室和贵族制作了大量的银制品。',
    },
    '496': {
        'id': '496',
        'name': '伪满兰花御纹章银酒杯',
        'list_name': '伪满兰花御纹章银酒杯',
        'category_id': '17',
        'category': '宫廷文物',
        'url': 'https://www.wmhg.com.cn/collection/detail/496.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d0746b00fc7d_3197_1489_376_0.JPG'],
        'desc': '简介：\n此件文物口径：4.5厘米，底径：4厘米，高：7.8厘米，重：39.1克。1938年10月1日（康德五年），伪满洲国赤十字社正式成立，此杯是伪满洲国皇后婉容，在该社建成之时的下赐之物。杯身上有兰花御纹章标记，杯底有伪满洲国赤十字社标识。',
    },
    '497': {
        'id': '497',
        'name': '伪满兰花御纹章浆汁斗',
        'list_name': '伪满兰花御纹章浆汁斗',
        'category_id': '17',
        'category': '宫廷文物',
        'url': 'https://www.wmhg.com.cn/collection/detail/497.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d07464ea8736_3054_1422_276_0.JPG'],
        'desc': '简介：\n此件文物通长：22厘米，宽：9厘米，高：11.2厘米，重：446克。此件浆汁斗为西餐具之一，用于盛着调味汁或肉汁，通常放在一个配套的餐盘上，以防浆汁顺口沿流下弄污桌布。此件浆汁斗质地为合金，形态敦厚，工艺精湛，主体器身为船形，前段宽流，后端有精美把手，便于把持和倒汁，底座为一圆盘，口沿和底座四周均有竖型条纹装饰，外壁中心有“兰花御纹章”标识。',
    },
    '498': {
        'id': '498',
        'name': '《大东亚战争画报》',
        'list_name': '《大东亚战争画报》',
        'category_id': '19',
        'category': '画报',
        'url': 'https://www.wmhg.com.cn/collection/detail/498.html',
        'images': ['/Uploads/Picture/2019/07/11/s5d26a2ead4799.jpg'],
        'desc': '简介：\n《大东亚战争画报》：共38册，印行于1942年至1945年间，日本大阪每日新闻社和东京日日新闻社发行。 在日本发动侵华战争的岁月里，大量的随军记者用他们的镜头记录了日寇所谓的“大和魂”，刊登于日本国内各种刊物之上，极力煽动日本民众的战争狂热，号召更多的青年为天皇效忠，参与实现世界“和平”的“大东亚圣战”。当日军在中国境内攻城掠地之时，日本的随军记者、摄影师与作家们，便遵照日本当局的指使，抢先报道日军的进攻与捷报，充当恶魔的吹鼓手；而当日军对东北民众实施血腥统治时，他们又连篇累牍地捏造伪满洲国的“祥和”景象，充当罪孽的粉饰工。在国家宣传机器的狂轰乱炸之下，日寇的“骄人”战绩如雨后春笋般涌现，这些比文字更具体、更形象、更有视觉冲击力的图片新闻，充斥着日本国民的神经，使军国主义深入民心，越来越多的民众开始狂热地、坚决地拥护的这场史无前例、罪孽深重的侵略战争。1945年8月15日，日本宣布无条件投降时，日本军部命令各新闻单位：“可当作战争见证的资料，必须全部销毁。”各媒体日以继夜地焚毁罪证，然而镜头下的谎言掩盖不住血写的事实，这些战争画报经过半个多世纪的辗转，又从日本回流到中国东北，成为日军暴行最有力的铁证。',
    },
    '507': {
        'id': '507',
        'name': '伪满国势调查纪念章',
        'list_name': '伪满国势调查纪念章',
        'category_id': '16',
        'category': '纪念章',
        'url': 'https://www.wmhg.com.cn/collection/detail/507.html',
        'images': ['/Uploads/Picture/2019/06/17/s5d07429fd7be1_5584_2607_442_0.JPG', '/Uploads/Picture/2019/06/17/s5d0742d45756a_5584_2607_322_0.JPG'],
        'desc': '简介：\n日本侵略者为了把伪满洲国挤身世界强国，成为独立国家的样子，效仿当时世界各国进行国势调查。在当时，哪个国家进行国势调查，就认为哪国家是文明国家。日本侵略者为全面掌控“满洲国”有多少财富可供其掠夺和利用，决定对伪满洲国进行国势调查，针对“满洲国”的土地、人口、经济等资源进行全面的普查。为配合这次国势调查，伪满洲国发纪念章一枚。铜质，直径3厘米，厚0.3 厘米，一面正中竖写有“满洲国势调查纪念章”，右侧写有“康德七年”，左侧写有“十月一日”。另一面底部阴刻“满洲国”地图，在地图上阳刻两个图案，上部为“伪满洲国兰花御纹章”，下部为伪满国务院办公大楼的剖面图。',
    },
    '1852': {
        'id': '1852',
        'name': '景仁宫御用地毯',
        'list_name': '景仁宫御用地毯',
        'category_id': '17',
        'category': '宫廷文物',
        'url': 'https://www.wmhg.com.cn/collection/detail/1852.html',
        'images': ['/Uploads/Picture/2020/02/18/s5e4b5e936e23d.jpg'],
        'desc': '景仁宫御用地毯,这块地毯原本长250厘米，宽145厘米，厚2厘米，用五彩毛线盘金织成。毯子正中织有“九凤朝阳”图案，毯边正中织有“景仁宫御用”五个字。这块地毯来自紫禁城景仁宫，景仁宫始建于明代初期，是明清两代后妃居所之一，清顺治帝第三子玄烨（即康熙）于1654年3月就出生在景仁宫，当时这块地毯就铺在景仁宫。同治帝的瑨妃在被赶出北京故宫时将这块地毯带出皇宫。\n溥仪很崇拜康熙，连伪满政权的年号“康德”都是取自“康熙”、“德宗”的合称。因此溥仪对康熙皇帝的遗物十分看重。伪满时期特意派人将这块地毯由北京送到长春宫内。溥仪十分珍爱这块地毯，作为一件重要藏品珍藏。平时很少铺用，只是在春节时才临时在缉熙楼的寝宫中铺几天。 1945年，溥仪在逃往通化大栗子沟之际还带走了这块地毯，在亡命之时还曾因这块地毯丢失而大发雷霆。后来这块地毯流传到一个开旅馆的人手中，“文革”前一直铺用。“文革”中因怕被这块地毯牵连，就存放在仓房中。当再想铺用时，由于保管不当已有多处腐烂，于是便裁剪成多块，有的垫在门前擦脚，有的送给邻居，剩下的用来垫鸡窝。\n1987年伪满皇宫博物院通过报纸、广播和电视向社会公开征集伪满皇宫失落于民间的珍贵文物。在了解这块地毯的情况后，把剩下的几块地毯征集入藏。这块地毯曾经经历了一个王朝的兴衰，虽然已经残破，无法复原，却依然默默地记录着那段历史。',
    },
}

EN: dict[str, dict] = {
    '1631': {
        'id': '1631',
        'name': 'Qibao Fengwen Bottle',
        'list_name': 'Qibao Fengwen Bottle',
        'category_id': '252',
        'category': 'Porcelain',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1631.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'brief introduction\nThis bottle of copper tyre, open, short neck, abundant shoulder, straight abdomen, flat foot. It is 36 centimetres high, 15.3 centimetres in diameter, 15.3 centimetres in base and 4720 grams in weight. It was fired in the period of the Puppet Manchu Dynasty. The bottle is full of golden enamel. In the center of the bottle, it depicts a colorful phoenix flying with wings. Its crown is red like a cock, and it is magnificent; its neck is blue like a snake, and its fluff is straight; its wings are green and brown and black like a peng, alternating from deep to light; its feet are brown like a crane, stretching naturally; and its tail is colorful like a peacock, elegant with the wind. This Phoenix looked down at the sky proudly at the moment of dancing, with noble and graceful manners, feathers stretching and strong momentum like a rainbow. Against the golden background, this Phoenix showed the king\'s presence in the world and the charm and elegance of the king of birds. Phoenix is also known as Phoenix Emperor, Crested Bird, Red Bird, Turkey and Quail Chicken. "Phoenix" and "phoenix" were originally two different kinds of divine birds in ancient mythology. Later generations usually interpreted Phoenix and Phoenix as the same kind of bird with different sexes, that is, the male is phoenix, the female is phoenix, and the male is phoenix. Phoenix, one of the four spirits of ancient Chinese animals, has the ability to rebirth from bathing fire, so it has the reputation of "immortal bird". Together with dragon, Phoenix and dragon constitute the two wings of traditional Chinese culture and symbolize the harmonious spirit of the Chinese nation in pursuit of "dragon and Phoenix are auspicious". Since ancient times, the Japanese people have also taken "bird" as totem, and influenced by Chinese traditional culture, they regard Phoenix as a divine bird, which implies auspicious meaning. The cultural origins of China and Japan can also be seen from this.',
    },
    '1632': {
        'id': '1632',
        'name': 'Blue and White Colored Flower Vase',
        'list_name': 'Blue and White Colored Flower Vase',
        'category_id': '252',
        'category': 'Porcelain',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1632.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'brief introduction\nThe bottle is 18.5 cm high, 9.6 cm in diameter, 13.8 cm in abdominal diameter, 9.9 cm in foot diameter and 1000 grams in weight. Open, hanging abdomen, circle foot, foot with blue and white book "today\'s right door" cursive style. The bottle is covered with white glaze and symmetrically painted flowers such as peony and chrysanthemum on both sides. Vertical stripes are painted near the foot for a week. This bottle of glaze is opalescent as congealed fat. Its composition is sparse and delicate. Its color is gorgeous and full. Blue and white are set off by adding color, reflecting the natural harmony.',
    },
    '1634': {
        'id': '1634',
        'name': 'Blue and white spherical tank',
        'list_name': 'Blue and white spherical tank',
        'category_id': '252',
        'category': 'Porcelain',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1634.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'Introduction:\nThe jar is 12.3 centimeters high, 3.1 centimeters in diameter, 9.3 centimeters in abdomen, 5.2 centimeters in foot and 480 grams in weight. Small mouth, spherical belly round, circle foot, foot white glaze, blue and white book "Jiugu Xushan" regular script. There are four layers of blue and white decoration on the whole body. Each layer is divided into four layers from top to bottom, each layer is separated by fine strings and white space; the mouth is decorated with beads along the bottom, and the shoulder is evenly distributed with eight thousand-word clusters; the abdomen has four lobes of diamond-shaped light, with lake pavilions and figures and trees painted inside; the four corners of the diamond are lined by three auspicious clouds, and the light-opening area is one with four leaves. Two continuous lines interval, near foot painting variant lotus pattern for a week.',
    },
    '1635': {
        'id': '1635',
        'name': 'Qibao Burning Chrysanthemum Vase',
        'list_name': 'Qibao Burning Chrysanthemum Vase',
        'category_id': '252',
        'category': 'Porcelain',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1635.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'Introduction:\nThe bottle is 61.5 centimeters high, 21.5 centimeters in diameter, 54.5 centimeters in foot diameter, and weighs 10723 grams. The color is jujube red, the embryo is silver, the open feet are big, the shoulder is wide and abdomen is abundant, the instrument is elegant and solemn, the glass texture is shining like water, the red is brilliant and dazzling. In the middle of the bottle, two blooming chrysanthemums are made by the silk pinching process, and several orchids are scattered in the lower right corner of the chrysanthemum. This bottle is a high-quality product in the Japanese Seven Treasures Burning.',
    },
    '1636': {
        'id': '1636',
        'name': 'Jiugu Colorful Flower and Bird Plate',
        'list_name': 'Jiugu Colorful Flower and Bird Plate',
        'category_id': '252',
        'category': 'Porcelain',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1636.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11.jpg', '/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'brief introduction\nThe outer edge of the plate is a curved nine-sided shape, each side recedes and rolls up slightly. The distance between the edges and the angle of the plate is 32.5 cm, 4.5 cm in height and 17.6 cm in foot diameter. The fetus is slightly green rat-colored and thick. The interior decoration pattern is flat and uniform, without density contrast. The theme includes flowers, trumpet birds, green bamboo, plum and stone. Although it is colorful, it has no sense of colour. Generally speaking, the color is not bright, and it appears astringent, quiet, simple and honest, and not gorgeous. Bird body green, deep glaze is now dark green, shallow peacock green; bird head, belly is yellow, color is even, is the most stable of several color glazes. Its flowers are purple, with a hint of Hibiscus stone, but with different shades. Painted on the back of the plate is decorated with pine, bamboo and plum at equal distances. The traveling money on the sole of the foot is a square handwritten word "Fu", covered with green glaze over the ink.',
    },
    '1637': {
        'id': '1637',
        'name': 'Xiduochuan Turtle Bran Travel Map',
        'list_name': 'Xiduochuan Turtle Bran Travel Map',
        'category_id': '253',
        'category': 'Japanese Painting',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1637.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'brief introduction\nThis Ukiyoshikawa Turtle Bran painting, Travel Picture, has a heart of 97 centimeters in length and 38.5 centimeters in cross. It is originally mounted in Japan. Its texture is silk. The picture is slightly yellowish. The mounting material is supported by a golden folding fan, giving people a sense of magnificence, which makes the whole painting full of nobility. This painting belongs to flesh-brush Ukiyoshi painting. To unfold this picture of "Travel Map", the first thing to be seen is a scenario of autumn travel. The distant hills are rolling and rolling. There are several flower branches in the prominent gaps on the right side of the picture. Flowers are blooming on the branches. The waterfalls flying down from the mountain stream are like white exercises, splashing a little water. The clouds and mists are in contrast with the water vapor, which set off the distant picture of clouds and mists, like fairyland. The four figures painted near the picture are the most. The woman in front is dressed in luxurious clothes and holds a piercing cypress folding fan symbolizing identity and grade. The noble and elegant gestures of the characters reveal the charm of classical beauty. Behind her were two maids, who held a pink umbrella in both hands to shade her from the sun, and looked back at the elephant behind her as if she was attracted to it; while another maid, with a box in both hands, followed the woman as if she were ready to wait for her messenger; and the little girl who followed her closely. Childish and naive, she followed behind the waitress, as if attracted by the beauty of her body can not bear to leave. Flowers are blooming behind them, and with gorgeous costumes, the whole picture is permeated with autumn charm everywhere. The costume color of the figure in the picture is distinct. The painter shows the gorgeousness and beauty of the costume. At the same time, he chooses the costume color strictly according to the social status and rank of the figure. Moreover, the gorgeous and noble dresses of women are properly displayed. The painter uses the method of contrast in the treatment of rocks and figures. The use of lines reflects the painter\'s character and interest, but also conveys the painter\'s delicate and rich connotation and emotions, and embodies the exquisite painting style of Turtle Bran, a Ukiyo painter, who is very good at expressing women\'s tenderness.',
    },
    '1638': {
        'id': '1638',
        'name': "Watanabe Huashan's Pictures of Crows in Cold Forest",
        'list_name': "Watanabe Huashan's Pictures of Crows in Cold Forest",
        'category_id': '253',
        'category': 'Japanese Painting',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1638.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663ac292816.jpg'],
        'desc': 'brief introduction\nAuthor: Watanabe Huashan (1793-1841), formerly known as Watanabe Dingjing, the word "An", the word "Boden", commonly known as Deng, the name of Huashan, mostly as the name of the world. Zhai Number includes Painting Hall, Pleasure Hall, Jin Hao Ju, Yesterday\'s non-resident and Sui An Ju. This painting belongs to Gaoyuan Landscape Painting, Paper Ink Painting, Vertical Axis, Exhibitory Paradise: "Tianbaoding You Jiaping Moon was written in the Pleasure Hall, Huashan Waisheng Stern." There are two metal stamps under the section: one is the rectangular seal "Gubao" in Baiwen Xiaozhuan and the other is the gourd-shaped "Deng" stamp in Zhuwen Xiaozhuan. This painting is vertical: 187 centimeters, horizontal: 67.4 centimeters; heart vertical: 124 centimeters, heart horizontal: 53 centimeters. The painting depicts a bleak scene of the late autumn wilderness, the migration of crows and the depression of all things. Peaks, bushes, streams, hills and stones, layered and intersected, scattered from near to far, from far to near; crows in groups swirling between thousands of cliffs; cold streams, close around the lonely barren mountains; winding steep paths, an old man holding his stick forward, a Book boy holding his piano behind him, shrouding the old man. Small is the cool feeling of late autumn and the lamentation of the forest. They want to go through the desolation and vastness of withered trees and cold forests and into the silence and desolation at the end of winter. The simple and unadorned picture, bold and unrestrained brushwork, ups and downs of the momentum, and the feelings of sorrow and autumn for thousands of miles express the author\'s deep concern about the unknown future of the Japanese nation and his helplessness and desolation in the valley of his life.',
    },
    '1639': {
        'id': '1639',
        'name': 'Watanabe Huashan The Daughter of the Knight',
        'list_name': 'Watanabe Huashan The Daughter of the Knight',
        'category_id': '253',
        'category': 'Japanese Painting',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1639.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': '作者：渡边华山(1793-1841)，原名渡边定静，字子安，一字伯登，通称登，号华山，多以此号行世。斋号有寓绘堂、全乐堂、金暾居、昨非居士、随安居士。\n此画作属华山青年时期的作品。此画为绢本设色，立轴，无题跋，署穷款：华山戏墨。通纵：125厘米，通横：68厘米；画心纵：40.5厘米，画心横：57厘米。画中所绘一位日本女子，身着和服，头饰素栉，双目凝神，回望飞燕，肌肤似雪，青丝如云，柳叶有情，樱桃微启，表现了江户时代贵族女子雍容华贵、安详恬静、风情万种的优雅神态。此画具有鲜明的日本民族风格和浓郁的人文精神，细微之处又显露出中国传统仕女绘画艺术的痕迹。画中人物仪态端庄，衣裳简劲，色彩柔丽，清雅中不失娇美，淡定中不失活力，在其扶栏顾盼的瞬间，生动唯美，气韵传神，流露出她丰富多情的内心世界和看似柔弱内敛、实则蓬勃坚韧的生命气质。常言道：“容情入境，心如其画”，此画表现了作者深邃细腻、志趣高雅的审美境界和独特精湛的艺术修养。',
    },
    '1640': {
        'id': '1640',
        'name': "Songcun Jingwen's Zen Fox Picture",
        'list_name': "Songcun Jingwen's Zen Fox Picture",
        'category_id': '253',
        'category': 'Japanese Painting',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1640.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'brief introduction\nAuthor: Matsumura Jingwen, a famous painter of the four schools of Yuanshan in the Edo period in Japan. Name Zhizhi, Zishizao, Zizao, Huaxi, commonly known as VIP. Born in Kyoto, Japan, the painter has a profound knowledge. He is the youngest brother of Wu Chun, the founder of the four schools.\nThe original name of Zen Fox Picture is Wild Fox Fishing Picture. It has a colored paper book, a vertical axis and a style of scenery. Longitudinal: 102.5 cm, horizontal: 43 cm; heart vertical: 27.8 cm, heart horizontal: 46 cm. This painting belongs to ink freehand brushwork, in which a fox is sitting with a scarf on his head, dressed in a skirt, with a silk ribbon around his waist, holding a bamboo stick in his right hand, with a calm and self-conscious manner. If his eyes are open and closed, he seems to be meditating and fishing with a pole, which is very monographic, persistent, full of interest and full of clumsiness. The brushwork is exquisite, with fresh ink, concise and lively, the combination of virtual and real, only a few strokes will outline a vivid, lovely, personified fox, smooth and simple ink lines, showing a strong style of Chinese Ming and Qing sketches. Except for the fox painted in the heart of the painting, there is nothing else in this work. This large area of blank space seems to give people a feeling of "all things recede, empty, invisible, silent to listen". However, in this invisible and colorless void, it contains the flow and precipitation of life, which sets off the infinite tenderness and beauty of the brush and ink in the painting. Strength gives people endless reverie.',
    },
    '1641': {
        'id': '1641',
        'name': 'Memorial Medallion for the Investigation of Puppet Manchukuo Situation',
        'list_name': 'Memorial Medallion for the Investigation of Puppet Manchukuo Situation',
        'category_id': '255',
        'category': 'Commemorative Medal',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1641.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'Introduction:\nIn order to make the puppet Manchuria a powerful country in the world and become an independent country, the Japanese aggressors followed the example of other countries in the world at that time to carry out state-of-the-art investigations. At that time, which country carried out the national situation survey, which country was considered to be a civilized country. In order to fully control the wealth of Manchuria, the Japanese aggressors decided to conduct a national survey of the puppet Manchuria and conduct a comprehensive census of its land, population, economy and other resources. In order to cooperate with the investigation, a memorial medal was issued by the puppet Manchukuo. Copper, 3 centimeters in diameter and 0.3 centimeters in thickness. On one side, a memorial badge for the investigation of Manchuria\'s national situation is written in the middle, Kant\'s Seven Years is written on the right, and October 1 is written on the left. On the other hand, a map of Manchukuo is engraved in the bottom, and two patterns are engraved in the sun on the map. The upper part is "Imperial Orchid of Manchukuo" and the lower part is a profile of the office building of Manchukuo State Council.',
    },
    '1642': {
        'id': '1642',
        'name': "Puppet Manchukuo's Meritorious Medal of Founding the People's Republic",
        'list_name': "Puppet Manchukuo's Meritorious Medal of Founding the People's Republic",
        'category_id': '255',
        'category': 'Commemorative Medal',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1642.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'brief introduction\nAfter consulting the "Senate Office" of Puyi, the chapter of meritorious service for the founding of the People\'s Republic was published and formulated in the form of "decree". The chapter is copper round, 30 cm in diameter, with the word "founding the country" embedded on the front. Each side of the word has a bow-shaped sorghum, and the ears of sorghum are also silver inlaid. On the back, from right to left, there are three vertical lines: "Great Manchuria", "Meritorious Medallion of the Founding of the People\'s Republic" and "First Year of Datong". The width of silk ribbon is 35 centimeters. It is composed of five kinds of flags symbolizing the harmony of the five nationalities of the Sun, Manchu, Chao, Meng and Han. Among them, black is 5 centimeters, white is 5 centimeters, yellow is 15 centimeters, red is 5 centimeters and blue is 5 centimeters. On March 1, 1934, while the puppet Manchukuo government realized monarchy, it promulgated a new organizational law, which stipulated that "the Emperor may be rewarded with other honors such as medals". In accordance with the regulations, the General Affairs Office of the State Council shall set up an Enjoyment Department, which shall be concurrently headed by the Personnel Department of the General Affairs Office, Junchuan Fengzhi. It shall consist of two sections, namely, general affairs and investigation, and shall be responsible for handling such matters as decorations, medals, commemorative medals and other honorary awards.',
    },
    '1643': {
        'id': '1643',
        'name': "Memorial Medallion of Emperor Puppet Manchu's Visit Day",
        'list_name': "Memorial Medallion of Emperor Puppet Manchu's Visit Day",
        'category_id': '255',
        'category': 'Commemorative Medal',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1643.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663bb23b6e2.jpg'],
        'desc': 'brief introduction\nIn order to commemorate Puyi\'s visit to Japan, the puppet Manchu government produced and issued a memorial medal. The design of the commemorative medal was commissioned by the famous Japanese sculptor Nishiko Shisan, who designed the medal and produced it by the Osaka Mint Bureau. The chapter is silver cymbal, 3.8 cm long, 3 cm wide and 0.35 cm thick. The surface is protruding. The front is carved with multi-layers of orchids symbolizing pseudo-Manchuria and chrysanthemums symbolizing Japan. Under the bouquet is carved with ribbons. On the ribbons are four characters of "one virtue and one heart". On the back, there are three lines inscribed from right to left: "Kant\'s Four Years", "Memorial Medallion of the Visiting Day of the Emperor of Manchuria" and "April 6". On the top of the chapter is a 6 cm long and 3.8 cm wide central dark purple with red ribbons on both sides. The width of red edge is 0.3 cm*2 and the width of central dark purple is 3.2 cm. According to the "Memorial Ordinance for the Visit Day of the Emperor of Manchuria" promulgated in September 1935, the scope of issuance of memorial medals is as follows: (1) those who are directly engaged in the imperial affairs of Kant\'s visit to Japan in April of the second year. (2) About those who accompany this important task. (3) He contributed to the emperor\'s visit to Japan.',
    },
    '1644': {
        'id': '1644',
        'name': "Establishment of Memorial Medals in the Temple of the Founding of the People's Republic of Manchukuo",
        'list_name': "Establishment of Memorial Medals in the Temple of the Founding of the People's Republic of Manchukuo",
        'category_id': '255',
        'category': 'Commemorative Medal',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1644.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663c6cb36b1.jpg'],
        'desc': 'brief introduction\nPuyi issued the Imperial Letter of Establishment of the Nation, which designated the "God of Heaven" as the "God of State" of the "Manchukuo". It is stipulated that July 15 of every year is the anniversary of the founding of the National Temple. It is a day off. Students and soldiers are required to recite the imperial edict like a stream. Those who fail to recite it or make mistakes will be severely punished. At the same time, the Puppet Manchukuo government also issued the Law on Punishment of Irreverence for the Founding of the People\'s Republic and its temples, which stipulates that anyone who passes through a temple should bow ninety degrees, or else be punished according to the Law on Irreverence Punishment. In order to commemorate this "great event", the puppet Manchu government also made a special "memorial medal for the founding of the temple". The medallion is brass, round, 3 cm in diameter and 0.3 cm in thickness, with circular perforation. The front of the memorial medal is the pattern of the "founding temple" in the Puppet Manchu Period, with the words "founding Temple founding Memorial medal" written in the middle on the back, Kant\'s seven years on the right and July 15 on the left.',
    },
    '1645': {
        'id': '1645',
        'name': 'Commemorative Medallion of the Puppet Manchu East Frontier Road',
        'list_name': 'Commemorative Medallion of the Puppet Manchu East Frontier Road',
        'category_id': '255',
        'category': 'Commemorative Medal',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1645.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'brief introduction\nIn order to commemorate the "success" of the campaign of "encirclement and suppression" of the anti-Japanese general Wang Fengge, the Japanese aggressors issued a very small number of "commemorative medals of the first expedition in the east" especially for the Japanese generals who participated in the "great expedition" on the east side road. The chapter is round, 5 cm in diameter, silver plated. On one side of the memorial medal, a cross belt is carved in the upper left corner of the sun, and a yellow Pentagon is carved in the middle. On the lower left side of the pentagon, there is "Yili". The middle part is separated by a river. The upper part of the river is a mountain jungle. Under the river, there is a winged bird. On the belly of the bird, there are three yellow words "Wang Feng Pavilion". On the other side, there are two lines at the top: the first line says "1937.3.27" and the second line says "The Eastern Front Road Strikes". Below is the topographic map of Dongbian Road, with the locations of Fengtian and Tonghua.',
    },
    '1646': {
        'id': '1646',
        'name': 'Artificial Manchurian Imperial Emblem Alloy Ring',
        'list_name': 'Artificial Manchurian Imperial Emblem Alloy Ring',
        'category_id': '256',
        'category': 'Cultural Relic',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1646.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'Introduction:\nThis cultural relic is 22 centimeters long, 9 centimeters wide, 11.2 centimeters high and 446 grams heavy. This unique shape of the utensil is Puyi and his royal members wash their hands before meals. Porcelain utensils mainly include Chinese wine cups, handle cups and discs, which are made by the Japanese Ceramic Society. Porcelain tires are light and thin as paper. The surface of porcelain is smooth and even, the shape is delicate and the decoration is elegant and concise.',
    },
    '1647': {
        'id': '1647',
        'name': 'Silver wine cup with imperial emblem of pseudo-orchid',
        'list_name': 'Silver wine cup with imperial emblem of pseudo-orchid',
        'category_id': '256',
        'category': 'Cultural Relic',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1647.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': "Introduction:\nThis cultural relic is 4.5 cm in diameter, 4 cm in base, 7.8 cm in height and 39.1 g in weight. On October 1, 1938 (Kant's Five Years), the Puppet Manchukuo Red Cross Society was officially established. This cup was the gift of the Puppet Manchukuo Empress Wanrong when the society was built. The cup is marked with an orchid imperial emblem and a false Manchurian Red Cross at the bottom.",
    },
    '1648': {
        'id': '1648',
        'name': 'Cuboid Sugar Box with Imperial Emblem of Pseudo-Manchurian Orchid',
        'list_name': 'Cuboid Sugar Box with Imperial Emblem of Pseudo-Manchurian Orchid',
        'category_id': '256',
        'category': 'Cultural Relic',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1648.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'Introduction:\nThe relic is 6.1 cm long, 4.8 cm wide, 2.3 cm high and 101 grams heavy. When the Manchukuo Palace was built, Puyi used it to hold the traditional Japanese candy "Jinping Sugar" at the banquet for ministers, which was similar to the sugar box given by Emperor Mikado. The lid of the box is marked with an orchid imperial emblem and the bottom is marked with the words "pure silver begotten foal". In 1870, Seven Raw Goose Shops were established in Osaka, Japan, specializing in the production of silver products and jewelry. In 1923, Shengju Corporation was officially established. The family business produced a large number of silver products for Japanese royalty and nobility.',
    },
    '1649': {
        'id': '1649',
        'name': 'Japans Showa and Sannian Chrysanthemum Imperial Emblem Spear Sugar Box',
        'list_name': 'Japans Showa and Sannian Chrysanthemum Imperial Emblem Spear Sugar Box',
        'category_id': '256',
        'category': 'Cultural Relic',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1649.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'Introduction:\nThis cultural relic is 3.5 centimeters long, 7 centimeters high and 80 grams heavy. The sugar box became popular after the Meiji Restoration. The earliest record was in Meiji 21 (1888). It was a regular gift given by the Emperor at banquets during various reception, celebrations and other ceremonial activities. Since then, some aristocrats have also learned the royal way to use it as a memorial to wedding celebrations and banquets related to the promotion of officials and nobles. This trend continues to expand, and military and political systems and business institutions have followed suit, but after World War II, it has basically restored to a state dominated by royalty. This sugar box is a gift from Emperor Hirohito when he took the throne. It is used to hold the traditional Japanese candy "Jinping Candy".',
    },
    '1650': {
        'id': '1650',
        'name': 'Silver Cup with Chrysanthemum Imperial Emblem in Showa, Japan',
        'list_name': 'Silver Cup with Chrysanthemum Imperial Emblem in Showa, Japan',
        'category_id': '256',
        'category': 'Cultural Relic',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1650.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'Introduction:\nThis cultural relic is 8.8 cm in diameter, 3.1 cm in foot diameter, 3.1 cm in height and 94.7 g in weight. On December 25, 1926, Emperor Dazheng died of illness and Emperor Hirohito ascended the throne. On November 10, 1928, Emperor Hirohito held a grand ceremony of inauguration in Kyoto. This cup was given by Empress Mikado at the time of the ceremony. It was engraved with sixteen eight-fold chrysanthemum patterns.',
    },
    '1651': {
        'id': '1651',
        'name': 'Pictorial of the Greater East Asian War',
        'list_name': 'Pictorial of the Greater East Asian War',
        'category_id': '258',
        'category': 'Pictorial',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1651.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg'],
        'desc': 'Introduction:\n"Pictorial of the Great East Asian War": A total of 38 copies were published between 1942 and 1945. They were issued by Japan\'s Osaka Daily News Agency and Tokyo Nippon News Agency. During the years when Japan launched the war of aggression against China, a large number of military correspondents used their cameras to record the so-called "Dahe Soul" of the Japanese aggressors, which was published in various domestic journals. They tried their best to incite the war fanaticism of the Japanese people, and called on more young people to be loyal to the Emperor and participate in the "Great East Asian Jihad" to achieve world "peace". " When the Japanese army attacked and plundered cities and lands in China, Japanese journalists, photographers and writers, following the instructions of the Japanese authorities, rushed to report the Japanese army\'s attacks and bulletins and acted as advocates of the devil. When the Japanese army exercised bloody rule over the people of the Northeast, they fabricated the "auspicious harmony" of the puppet Manchuria. ” Scene, as the Whitewasher of sin. Under the bombardment of the national propaganda machine, the "proud" achievements of the Japanese aggressors sprang up like bamboo shoots after a spring rain. These pictures and news, which are more specific, more vivid and more visual than words, are full of the nerves of the Japanese people, making militarism deeply rooted in the hearts of the people. More and more people begin to enthusiastically and firmly support it. This unprecedented and sinful war of aggression. On August 15, 1945, when Japan announced its unconditional surrender, the Japanese Military Department ordered all news units to "destroy all materials that can be used as war witnesses." The media burned the evidence day and night, but the lies on camera could not hide the fact of bloody writing. After more than half a century of tossing and turning, these war pictorials returned from Japan to Northeast China and became the most powerful evidence of Japanese atrocities.',
    },
    '1652': {
        'id': '1652',
        'name': 'Premier Yuweng Zhou went to think about Memorial bronze mirrors',
        'list_name': 'Premier Yuweng Zhou went to think about Memorial bronze mirrors',
        'category_id': '257',
        'category': 'Bronze Mirror',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1652.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'Introduction:\nThe bronze mirror is 41.3 cm in diameter, 1.6 cm in edge thickness, 6320 g in weight, round, straight in body, flat button top, plain wide edge, huge in volume. Inscriptions are spread all over the mirror from right to left: at the top, the central seal character is used to cast "Buddha of ten thousand families"; on the right side is "Yuweng Zhou County Governor goes to think about memorial"; on the left side is "Acheng County\'s political gentry, business and agronomy". Songs from all walks of life. The circle is the oldest and most traditional shape of Chinese bronze mirrors. It is also a symbol of fullness, integrity, auspiciousness, beauty and abundance. To think about it is to say that the local scholars and people miss the departed officials. He Wuzhuan in the Han Dynasty reads: "If you want to get rid of officials, you should take precautions against entrusting them. They also live in an unknown place and think often after you leave." The italic text in the central mirror expresses the respect and remembrance of the former county governor from all walks of life in Acheng County, as well as the praise of his achievements and virtues. The mirror back is centered around the mirror button, with the inscription "Fushou Rongxiang" cast on the left and right sides, and the inscription "Lujiabao Chang" cast on both sides of the top "Fujiabao" is the name of the mirror casting workshop in Acheng County at that time. The "Lujiabao Chang" is a guarantee and commitment to the quality of its bronze mirror.',
    },
    '1653': {
        'id': '1653',
        'name': 'Bronze Mirror in Memory of Guandong Church of Yueyue Religion',
        'list_name': 'Bronze Mirror in Memory of Guandong Church of Yueyue Religion',
        'category_id': '257',
        'category': 'Bronze Mirror',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1653.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663c6cb36b1.jpg', '/Uploads/Picture/2019/08/28/s5d663c2a943fa.jpg'],
        'desc': 'Introduction:\nThe bronze mirror is 7.6 cm in diameter, 0.7 cm in edge thickness and 189.7 g in weight. Its shape is anise sunflower, round button and narrow edge. Inscribed on the mirror is a Japanese inscription to the effect that "self-reflection on the mirror every day can cultivate body and mind". The mirror back is centered on the mirror button, with two phoenix feet stepping on the auspicious clouds, dancing relatively, the Phoenix body is rich and supple, the Phoenix feet are graceful and graceful, and the Phoenix Tail flies and stretches. When the two phoenixes spread their wings in the wind, the flower belts tied to their necks fluttered along with them, lifelike. On the top of the two phoenixes, where the Phoenix tails are crowded, there is a hexagonal decoration; under the mirror, there is an inscription: "The 30th anniversary of the opening of Yueyue Guandong Church". This bronze mirror was cast in 1942 to celebrate the 30-year opening of Yueyue Guandong Church in Northeast China. It can be seen from this that Shintoism, as the national religion of the puppet Manchuria, is an important tool for aggressors to rule and fool the people\'s thoughts in Northeast China. Religious aggression is the "spiritual opium" of Japanese colonial rule.',
    },
    '1654': {
        'id': '1654',
        'name': 'Bronze Mirror of Zhongling Tower',
        'list_name': 'Bronze Mirror of Zhongling Tower',
        'category_id': '257',
        'category': 'Bronze Mirror',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1654.html',
        'images': ['/Uploads/Picture/2019/08/28/s5d663065d3d11_1630_762_0_0.jpg', '/Uploads/Picture/2019/08/28/s5d663ae388923_2140_1001_0_0.jpg'],
        'desc': 'Introduction:\nThe bronze mirror is 7.6 cm in diameter, 0.6 cm in edge thickness, 192.4 g in weight, multi-lateral sunflower-shaped, without mirror buttons, narrow edge, and copper in texture. The mirror is slightly convex, with a Japanese inscription in the middle circle to the effect that the name of the Imperial officer who died in battle for the country will be engraved on the tower of loyalty forever, and will remain in the fragrance forever for the 260th anniversary of the epoch. The mirror back is divided into inner and outer areas by the ideal curve. The theme of the inner area is prominent. The high relief sculpture "Zhongling Tower" shows radial stripes above the tower, which implies "a great deal of light". The lake water and flowers surround the tower below. The inscription "Xinjing" is cast on the top of the outer area, and the rest of the space is decorated with flowers and plants. The bottom edge of the mirror is no longer a sunflower curve, but a knife pattern. This bronze mirror with the pattern of the loyal spiritual pagoda of the pseudo-Manchukuo "Xinjing" was cast in 1940 to celebrate the 2600-year-old first year of the Japanese Emperor\'s reign. Japan is a Shinto country. The Japanese nation claims to be the descendant of the "God of Heaven". From the birth of Emperor Shenwu to the reign of Emperor Hirohito in Zhao and 17 years, it happens to be 2600 years. Therefore, this year has become a once-in-a-century festival in Japan. The puppet Manchukuo under the eggs of the Japanese Kwantung Army also held various celebrations and commemorative activities under the direction of its masters and sons. The casting of this bronze mirror, on the one hand, commemorates the dead of Japan in the war of aggression, deceives the people of Japan and the puppet army of Northeast China to continue to work hard for the Jihad in Greater East Asia; on the other hand, forces the people of Northeast China to celebrate the birth of the Japanese Mikado system in 2600 years, and then publicizes "the unity of day and man" and "the unity of virtue" to China. The people practise ideological anaesthesia and spiritual slavery.',
    },
    '1793': {
        'id': '1793',
        'name': 'Collection testdata Porcelain Blue and white color flower bottle',
        'list_name': 'Collection testdata Porcelain Blue and white color flower bottle',
        'category_id': '252',
        'category': 'Porcelain',
        'url': 'https://www.wmhg.com.cn/en/collection/detail/1793.html',
        'images': ['/Uploads/Picture/2019/09/06/s5d71f945e74a4.png', '/Uploads/Picture/2019/09/06/s5d71f94f6afa1.png'],
        'desc': 'The bottle is 18.5 cm high, 9.6 cm in diameter, 13.8 cm in diameter, 9.9 cm in diameter and 1000 g in weight. Open, drooping, circled, and the foot of the blue-and-white book "now right door" cursive. The whole body is white glazed, and the sides of the bottle are symmetrically painted with flowers such as peony and chrysanthemum, and the vertical stripes are painted around the foot for one week. This bottle of glaze is as white as gelatin, the composition is sleek and sleek, the color is bright and full, the blue and white are complemented by the contrast, which reflects the natural harmony.',
    },
}
